// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reservas.API.Data;

#nullable disable

namespace Reservas.API.Migrations
{
    [DbContext(typeof(ReservasContext))]
    partial class ReservasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reservas.API.Models.Espacio", b =>
                {
                    b.Property<int>("IdEspacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspacio"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdEspacio");

                    b.ToTable("Espacios");
                });

            modelBuilder.Entity("Reservas.API.Models.EstadoReserva", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdEstado");

                    b.ToTable("EstadosReserva");
                });

            modelBuilder.Entity("Reservas.API.Models.HistorialReserva", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorial"));

                    b.Property<int>("EstadoIdEstado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer");

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReservaIdReserva")
                        .HasColumnType("integer");

                    b.HasKey("IdHistorial");

                    b.HasIndex("EstadoIdEstado");

                    b.HasIndex("ReservaIdReserva");

                    b.ToTable("HistorialReservas");
                });

            modelBuilder.Entity("Reservas.API.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("DniUsuario")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReservaIdReserva")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioDni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("ReservaIdReserva");

                    b.HasIndex("UsuarioDni");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Reservas.API.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("DniUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EstadoReservaIdEstado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEspacio")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("IdReserva");

                    b.HasIndex("DniUsuario");

                    b.HasIndex("EstadoReservaIdEstado");

                    b.HasIndex("IdEspacio");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Reservas.API.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Reservas.API.Models.Usuario", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RolIdRol")
                        .HasColumnType("integer");

                    b.HasKey("Dni");

                    b.HasIndex("RolIdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Reservas.API.Models.HistorialReserva", b =>
                {
                    b.HasOne("Reservas.API.Models.EstadoReserva", "Estado")
                        .WithMany("Historiales")
                        .HasForeignKey("EstadoIdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservas.API.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaIdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Reservas.API.Models.Notificacion", b =>
                {
                    b.HasOne("Reservas.API.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaIdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservas.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Reservas.API.Models.Reserva", b =>
                {
                    b.HasOne("Reservas.API.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("DniUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservas.API.Models.EstadoReserva", null)
                        .WithMany("Reservas")
                        .HasForeignKey("EstadoReservaIdEstado");

                    b.HasOne("Reservas.API.Models.Espacio", "Espacio")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEspacio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Reservas.API.Models.Usuario", b =>
                {
                    b.HasOne("Reservas.API.Models.Rol", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RolIdRol");
                });

            modelBuilder.Entity("Reservas.API.Models.Espacio", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Reservas.API.Models.EstadoReserva", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Reservas.API.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Reservas.API.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
